### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by lexeech** [Bazzcola/EBS-MOVIES#1]
## issues
1. [there's no loader](https://user-images.githubusercontent.com/28218829/89168348-692aca00-d585-11ea-8685-76708ef9bb92.png)
2. [can't navigate through movie profile](https://user-images.githubusercontent.com/28218829/89168480-9b3c2c00-d585-11ea-969f-c4e888ef253e.png)
3. use fetch instead of axios

**Comment by Bazzcola** [comment]
done
